---

- name: Install supervisord
  apt: name=supervisor

- name: Install supervised processes
  template: src=process.conf dest=/etc/supervisor/conf.d/{{ supervisor_process_name }}.conf

- name: Make sure supervisord is running
  systemd: name=supervisor state=started
  when: ansible_distribution_release == 'xenial'

- name: Make sure process group is present
  supervisorctl: name={{ supervisor_process_name }} state=present

- name: Stop process group
  supervisorctl: name={{ supervisor_process_name }} state=stopped

- name: Start process group
  supervisorctl: name={{ supervisor_process_name }} state=started

- name: Logging permissions
  file: path={{ supervisor_log_directory }}
        state=directory
        group={{ supervisor_process_user }}
        owner={{ supervisor_process_user }}
