---

- name: Install supervisord
  apt: name=supervisor

- name: Install supervised processes
  template: src=process.conf dest=/etc/supervisor/conf.d/{{ supervisor_process_name }}.conf
  notify:
    - supervisor process restart

- name: Make sure process group is present
  supervisorctl: name={{ supervisor_process_name }} state=present
  notify:
    - supervisor process restart

- name: Logging permissions
  file: path={{ supervisor_log_directory }}
        state=directory
        group={{ supervisor_process_user }}
        owner={{ supervisor_process_user }}
